In [64]:
import pandas as pd
from sklearn.cluster import MeanShift

In [65]:
data = pd.read_table('./201309_foursquare_dataset_umn/fsq/umn_foursquare_datasets/checkins.dat', sep= '|', skipinitialspace=True, skiprows=[1])

/home/roma/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.
/home/roma/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [66]:
data.dropna(inplace=True)
data.columns = data.columns.str.strip()
data.set_index('id')
data.sort_index()

id    user_id   venue_id   latitude   longitude  \
1         984222    15824.0     5222.0  38.895112  -77.036366   
3         984234    44652.0     5222.0  33.800745  -84.410520   
7         984291   105054.0     5222.0  45.523452 -122.676207   
9         984318  2146539.0     5222.0  40.764462 -111.904565   
10        984232    93870.0   380645.0  33.448377 -112.074037   
11        984483  1030290.0   955969.0  32.221743 -110.926479   
12        984685   304253.0    23558.0  40.650000  -73.950000   
13        984470   720850.0   749715.0  33.448377 -112.074037   
15        984610  1639666.0   442605.0  33.414768 -111.909309   
18        984653  1647192.0    23558.0  42.358431  -71.059773   
19        984251   298547.0    77014.0  33.448377 -112.074037   
20        984528  2046311.0    15682.0  33.414768 -111.909309   
25        984438  2096701.0     4432.0  33.448377 -112.074037   
26        984277  1648816.0    18006.0  33.248664 -111.634299   
27        984320   349414.0      819.0  32.840678 -117.258794   
29        984359  1861538.0      819.0  34.052234 -118.243685   
34        984294  1447044.0  1135957.0  33.414768 -111.909309   
35        984336  2064557.0   111071.0  33.448377 -112.074037   
38        984527  1243334.0   989443.0  34.483901 -114.322455   
40        984326  2046338.0   989443.0  34.048928 -111.093731   
41        984454  2098254.0   610703.0  32.715329 -117.157255   
42        984395  1508584.0   410624.0  33.448377 -112.074037   
46        984231  1868751.0    21948.0  38.895112  -77.036366   
47        984322  1096457.0    10935.0  33.745851 -117.826166   
49        984474  2146888.0    10935.0  34.096111 -118.105833   
50        984355   966186.0    10935.0  34.052234 -118.243685   
52        984345   482032.0    10935.0  37.629349 -122.400087   
53        984508  2146895.0    10935.0   4.598056  -74.075833   
54        984381    28655.0    10935.0  33.804167 -118.158056   
55        984346  2098173.0    11195.0  40.735657  -74.172367   
...          ...        ...        ...        ...         ...   
1021885  936189    610763.0     7491.0  41.499495  -81.695409   
1021887  936836    610763.0       64.0  41.499495  -81.695409   
1021890  937236    287341.0     9310.0  30.267153  -97.743061   
1021895  938393    379311.0    11138.0  39.739154 -104.984703   
1021896  938627    503977.0     6562.0  28.538335  -81.379237   
1021898  938806    287341.0    12004.0  30.267153  -97.743061   
1021901  940180   1028835.0    16436.0  42.129224  -80.085059   
1021902  940219    373497.0     7489.0  40.715972  -74.001437   
1021912  943071    404031.0  1095987.0  33.448377 -112.074037   
1021915  943920    706143.0     4432.0  35.960638  -83.920739   
1021916  944155    872108.0    54467.0  33.103174  -96.670550   
1021918  944731    502383.0    23558.0  41.650111  -70.241131   
1021923  946195    354912.0    29137.0  39.867891  -75.131565   
1021925  946253    281860.0    29488.0  28.538335  -81.379237   
1021936  949275    872108.0   610705.0  33.103174  -96.670550   
1021939  949841    281860.0     9822.0  28.538335  -81.379237   
1021940  951412    919527.0   112490.0  47.606209 -122.332071   
1021943  952256   1028835.0     8595.0  42.129224  -80.085059   
1021947  953584    174305.0   916378.0  28.320007  -80.607551   
1021949  953695    146164.0     4202.0  30.267153  -97.743061   
1021952  954162    285893.0    42311.0  33.448377 -112.074037   
1021953  954283    709109.0   684720.0  33.448377 -112.074037   
1021954  954361     81625.0     5222.0  37.629349 -122.400087   
1021955  954428    626076.0   950644.0  40.850100  -73.866246   
1021957  954925    674797.0     7491.0  33.748995  -84.387982   
1021959  955561    626076.0    20073.0  40.850100  -73.866246   
1021960  955892    674797.0     2297.0  33.748995  -84.387982   
1021961  956377    845102.0    11195.0  42.765366  -71.467566   
1021962  956119   1139114.0    29488.0  42.439479  -83.743830   
1021964  956733    960666.0       60.0  42.331427

In [67]:
X  = data[['latitude','longitude']][:100001]

In [68]:
ms = MeanShift(bandwidth=0.1)
ms.fit(X)

MeanShift(bandwidth=0.1, bin_seeding=False, cluster_all=True, min_bin_freq=1,
          n_jobs=None, seeds=None)

In [69]:
ms.cluster_centers_

array([[  40.7177164 ,  -73.99183542],
       [  33.44943805, -112.00213969],
       [  33.44638027, -111.90188756],
       ...,
       [ -37.8229826 ,  145.1811902 ],
       [ -41.2924945 ,  174.7732353 ],
       [ -45.0311622 ,  168.6626435 ]])

In [70]:
#new DataFrame from results
data_clustered = pd.DataFrame({"latitude": X.values[:,0],'longitude':X.values[:,1], "label": ms.labels_})
data_clustered.head()

latitude   longitude  label
0  38.895112  -77.036366      5
1  33.800745  -84.410520      7
2  45.523452 -122.676207     30
3  40.764462 -111.904565     65
4  33.448377 -112.074037      1

In [71]:
#Group by counts to sort > 15 checkins
data_sorted = data_clustered.groupby('label').count()

In [72]:
clusters = data_sorted[data_sorted.latitude > 15].reset_index().label.values

In [73]:
centers = []
for i in clusters:
    centers.append(ms.cluster_centers_[i])

In [74]:
import numpy as np
centers_np = np.array(centers)
centers_np

array([[  40.7177164 ,  -73.99183542],
       [  33.44943805, -112.00213969],
       [  33.44638027, -111.90188756],
       ...,
       [  41.61853175,  -88.44556818],
       [  39.2494686 ,  -77.1821271 ],
       [  38.65877915,  -76.8856871 ]])

In [75]:
#Create offices array
offices = np.array([[33.751277, -118.188740],
                    [25.867736, -80.324116],
                    [51.503016, -0.075479],
                    [52.378894, 4.885084],
                    [39.366487, 117.036146],
                    [-33.868457, 151.205134]])

In [76]:
#Calculate distance
def distance(point1, point2):
    return ((point1[0] - point2[0])**2 + (point1[1] - point2[1])**2)**0.5

In [57]:

answer_index = 0
min_dist = 0
i = 0
while i < len(centers_np):
    distances = [distance(xx, centers_np[i]) for xx in offices]
    if min_dist == 0:
        min_dist = min(distances)
        answer_index = i
    else:
        if min_dist > min(distances):
            min_dist = min(distances)
            answer_index = i
    i += 1

In [58]:
answer_index

417

In [59]:
min_dist

0.007834758163107856

In [60]:
centers_np[answer_index]

array([-33.86063043, 151.20477593])

In [61]:
def write_answer(center):
    with open("answer.txt", "w") as f:
        f.write(str(center[0]) + ' ' + str(center[1]))

In [62]:
write_answer(centers_np[answer_index])